### ISSUE TITLE
Popper.js v1 is out

### ISSUE THREAD

**Issue by FezVrasta** [cypress-io/react-tooltip#1]
Hi, just wanted to let you know that the v1 is out, maybe you want to update your component.

**Comment by nihiluis** [comment]
yeah

**Comment by nihiluis** [comment]
I think one can update it by replacing the following method in portal-popper.jsx
i'm not sure if applyStyle should be enabled though

I replaced the deprecated modifiersIgnored and updated the onUpdate callback to the new syntax.


```
componentDidMount () {
    this.popper = new this.props.Popper(this.props.getTargetNode(), this.refs.popper.domNode, {
        content: this.props.title,
        placement: this.props.placement,
      modifiers: {
        applyStyle: {
          enabled: true
        },
        arrow: { 
          element: this.refs.arrow
        }
      }
})

    this.popper.onUpdate = (data) => {
      if (this.isUnmounted) return

      const newState = {}
      if (data.offsets.arrow) newState.arrowProps = data.offsets.arrow
      if (data.offsets.popper) newState.popperProps = data.offsets.popper
      this.setState(newState)
    }

    this.popper.update()
  }
```

**Comment by chrisbreiding** [comment]
@FezVrasta Thanks for the heads up! I'll upgrade as soon as I get a chance. Great library btw!

@nihiluis That's great - thanks for doing the legwork!

**Comment by chrisbreiding** [comment]
Upgraded as of `0.1.4`
