### ISSUE TITLE
Update CircleCI Node Docker Image

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/react-tooltip#193]
Notice on https://circleci.com/docs/2.0/circleci-images/ reads:

> Legacy images with the prefix "circleci/" will be [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) on December 31, 2021. For faster builds, upgrade your projects with [next-generation convenience images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).

Update `.circle.yml` to use [`cimg/node`](https://hub.docker.com/r/cimg/node).

**Comment by chrisbreiding** [comment]
Fixed by https://github.com/cypress-io/react-tooltip/pull/226
