### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by flotwig** [cypress-io/react-tooltip#20]
Getting this error intermittently while viewing snapshots in Cypress and then trying to hover over the snapshot controls while the snapshot disappears.

![image](https://user-images.githubusercontent.com/1151760/61534241-11163980-a9fd-11e9-967d-78314fa1cceb.png)

Thinking that we should just wrap `.removeChild` in a try/catch, or check if `this._element` is still a child of `appendTo`.

**Comment by chrisbreiding** [comment]
Sounds good. I'll knock this out.
